server.port=11055

# configuracion para conectar la bd
spring.datasource.url=jdbc:mysql://localhost:3306/aplicacion5c?createDatabaseIfNotExist=true
spring.datasource.username=estudiante
spring.datasource.password=estudiante
# configurar compatibilidad con mysql
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# configuracion para gestionar la estructura de mi bd
spring.jpa.hibernate.ddl-auto=update